#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket..."
        # -S: Start, -b: Background, -m: Make PID file, -x: Executable
        start-stop-daemon -S -b -m -p /var/run/aesdsocket.pid -x /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket..."
        start-stop-daemon -K -p /var/run/aesdsocket.pid
        rm -f /var/run/aesdsocket.pid
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0